name: code_zero
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pull_to_refresh: 2.0.0
  flutter_screenutil: 5.5.3+2
  flutter_easyloading: 3.0.5
  cached_network_image: 3.2.0
  dio: 4.0.6
  sp_util: 2.0.3
  package_info: 2.0.2
  event_bus: 2.0.0
  oktoast: 3.1.5
  flutter_svg: 1.0.3
  device_info: 2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_ume: ^0.3.0+1
  flutter_ume_kit_ui: ^0.3.0+1
  flutter_ume_kit_device: ^0.3.0
  flutter_ume_kit_perf: ^0.3.0
  flutter_ume_kit_show_code: ^0.3.0
  flutter_ume_kit_console: ^0.3.0
  flutter_ume_kit_dio: ^0.3.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/shopping_cart/
  uses-material-design: true

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/assets
  compress_images: false

flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: generated/assets
  # Optional. Sets whether utomatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: true
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: assets
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: Assets