name: code_zero
version: 1.0.8+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pull_to_refresh: 2.0.0
  flutter_screenutil:
    git:
      url: git@github.com:Crazy-MT/flutter_screenutil.git
      ref: f1a58a6610e421c12663caa9441f2356331100de
  flutter_easyloading: 3.0.5
  cached_network_image: 3.2.0
  dio: 4.0.6
  sp_util: 2.0.3
  package_info_plus: 1.4.0
  event_bus: 2.0.0
  oktoast: 3.1.5
  flutter_svg: 1.0.3
  device_info: 2.0.3
  url_launcher: 6.1.5
  image_picker: 0.8.6
  image_picker_for_web: 2.1.10
  image_picker_platform_interface: 2.6.1
  file_selector: 0.9.2+2
  image_cropper: 3.0.0
  date_format: 2.0.6
  qr_flutter: 4.0.0
  permission_handler: 10.0.0
  image_gallery_saver: 1.7.1
  flutter_html: 3.0.0-alpha.2
  path_provider: 2.0.11
  flutter_pickers: 2.1.8
  text_scroll: 0.1.0
  badges: 2.0.3
  webview_flutter: 3.0.4
  card_swiper: 2.0.4
  photo_view: 0.14.0
  fluwx: 3.9.2
  r_upgrade: #0.4.0 #https://github.com/rhymelph/r_upgrade/blob/master/README_CN.md
    git: git@github.com:Crazy-MT/r_upgrade.git
  platform_device_id: 1.0.1
  image_downloader_web: 1.0.2
  image_crop_widget: ^0.0.6
#  flutter_image_editor: ^1.2.0
  image_editor: any
  image: any
  dotted_border: 2.0.0+3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  universal_platform: 1.0.0+1

dev_dependencies:
  flutter_lints: 1.0.0
  flutter_ume: 1.0.2+1
  flutter_ume_kit_ui: 1.0.0
  flutter_ume_kit_device: 1.0.0
  flutter_ume_kit_perf: 1.0.0
  flutter_ume_kit_show_code: 1.0.0
  flutter_ume_kit_console: 1.0.0
  flutter_ume_kit_dio: 1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/html/
    - assets/icons/
    - assets/images/
    - assets/images/dialog_bg/
    - assets/images/shopping_cart/
  uses-material-design: true

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/assets
  compress_images: false